#pragma once

typedef struct _wall	*WALL;
typedef struct _weapon	*WEAPON;
typedef struct _castle	*CASTLE;
typedef struct _mine	*MINE;
typedef struct _player	*PLAYER;
typedef struct _team	*TEAM;
typedef struct _game	*GAME;

void			calculateATeam(TEAM, char *);
void			calculateACastle(CASTLE, char *);
void			calculateAMine(MINE, char *);
void			getTeamPlayerString(GAME, char *);
void			getGameProperties(GAME, char *);
void			informGameRoomChange(GAME, int, char *, char *, char *);
void			loadAccountMap(char *);
void			addNewAccount(char *, char *, char *);
void			Swap(PLAYER, PLAYER, WSAEVENT, WSAEVENT);
void			sendGameRoomMessageToAllPlayersInGameRoom(GAME, int, char *);
void			sendInGameMessageToAllPlayersInGameRoom(GAME, int, char *, char *);
void			clearPlayerInfo(PLAYER, char *);
int				Communicate(PLAYER, char *, char *);
int				Send(PLAYER, char *, int, int);
int				Receive(PLAYER, char *, int, int);
int				receiveAndProcessPayload(PLAYER, char *, int, char *, char *);
int				handleLogin(PLAYER, char *, char *);
int				handleSignUp(PLAYER, char *, char *);
int				handleCreateGame(PLAYER, char *, char *);
int				handleGetLobby(PLAYER, char *, char *);
int				handleJoinGame(PLAYER, char *, char *);
int				handleChangeTeam(PLAYER, char *, char *);
int				handleReadyPlay(PLAYER, char *, char *);
int				handleUnreadyPlay(PLAYER, char *, char *);
int				handleQuitGame(PLAYER, char *, char *);
int				handleStartGame(PLAYER, char *, char *, char *);
int				handleKick(PLAYER, char *, char *);
int				handleLogOut(PLAYER, char *, char *);
int				handleAttackCastle(PLAYER, char *, char *, char *);
int				handleAttackMine(PLAYER, char *, char *, char *);
int				handleBuyWeapon(PLAYER, char *, char *, char *);
int				handleBuyWall(PLAYER, char *, char *, char *);
int				handleCheat(PLAYER, char *, char *, char *);
int				setResponseAndSend(PLAYER, char *, char *, int, char *);
void			emptyGame(GAME);
void			getLobbyList(char *);
void			getGameInfo(GAME, char *);
long long		getTime();